=== kafawi/PMP2/bin/aufgabenblatt1/pi.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pi (sensor)*>
<!ATTLIST pi name CDATA #REQUIRED ip CDATA #REQUIRED>
<!ELEMENT sensor (typ?, wert?)>
<!ATTLIST sensor ort CDATA #REQUIRED>
<!ELEMENT typ (#PCDATA)>
<!ELEMENT wert (#PCDATA)>

=== kafawi/PMP2/src/aufgabenblatt1/Raspberry.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pi SYSTEM "pi.dtd">
<pi name="Raspberry Pi - Model b" ip="192.168.2.1">
	<sensor ort="Wohnzimmer">
		<typ>Temperatur</typ>
		<wert>22.4</wert>
	</sensor>
	<sensor ort="KÃ¼che">
		<wert>-1.2323</wert>
	</sensor>
	<sensor ort="Badezimmer">
		<typ>Luftfeuchtigkeit</typ>
		<wert>63.8</wert>
	</sensor>
</pi>
